# Generated by Django 5.0.2 on 2024-03-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0002_alter_empresa_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen',
            field=models.ImageField(default='corp/images/default.png', upload_to='corp/images/'),
        ),
    ]
