# Generated by Django 5.0.2 on 2024-03-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0004_empresa_nivel_marca_empleadora_empresa_salario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='redes',
            field=models.TextField(default='N/A'),
        ),
    ]
