# Generated by Django 5.0.2 on 2024-03-19 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0005_empresa_redes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='vacantes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
