# Generated by Django 5.0.2 on 2024-05-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='Fecha_extraccion',
            field=models.DateField(default='2024-05-05'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='banner_empresa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='calificacion_empresa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='extraido_de',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_beneficios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_entrevistas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_evaluaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_fotos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_ofertas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_salarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='seguidores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subtitle2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subtitle2_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subtitle_content',
            field=models.TextField(blank=True),
        ),
    ]
