# Generated by Django 5.0.2 on 2024-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0002_empresa_fecha_extraccion_empresa_banner_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='Fecha_extraccion',
            field=models.DateField(default='2024-05-05', null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='calificacion_empresa',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='extraido_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_beneficios',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_entrevistas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_evaluaciones',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_fotos',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_ofertas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_salarios',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='seguidores',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='subtitle2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='subtitle2_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='subtitle_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
