# Generated by Django 5.0.2 on 2024-05-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0003_alter_empresa_fecha_extraccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='calificacion_ambiente_trabajo',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='calificacion_director_general',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='calificacion_oportunidades_carrera',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='calificacion_salario_prestaciones',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Fecha_extraccion',
            field=models.DateField(default='2024-05-06', null=True),
        ),
    ]
