# Generated by Django 5.0.2 on 2024-05-13 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0004_empresa_calificacion_ambiente_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='Fecha_extraccion',
            field=models.DateField(default='2024-05-13', null=True),
        ),
        migrations.CreateModel(
            name='ComentariosComputrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.CharField(blank=True, max_length=255, null=True)),
                ('contenido', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscraping.empresa')),
            ],
        ),
    ]
