# Generated by Django 5.0.2 on 2024-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0009_remove_comentarioscomputrabajo_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioscomputrabajo',
            name='reportes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='comentariospropios',
            name='reportes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Fecha_extraccion',
            field=models.DateField(default='2024-05-17', null=True),
        ),
    ]
