# Generated by Django 5.0.2 on 2024-05-11 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corp', '0011_alter_empresa_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='credenciales/imagen_default.png', upload_to='credenciales/')),
                ('redes', models.TextField(default='N/A')),
                ('empresas_favoritas', models.ManyToManyField(blank=True, null=True, to='corp.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
