# Generated by Django 5.0.2 on 2024-05-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0011_alter_empresa_id'),
        ('credenciales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credenciales',
            name='empresas_favoritas',
            field=models.ManyToManyField(to='corp.empresa'),
        ),
    ]
