# Generated by Django 5.0.2 on 2024-05-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0011_alter_empresa_id'),
        ('credenciales', '0002_alter_credenciales_empresas_favoritas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credenciales',
            name='empresas_favoritas',
            field=models.ManyToManyField(default=[], to='corp.empresa'),
        ),
        migrations.AlterField(
            model_name='credenciales',
            name='imagen',
            field=models.ImageField(default='/credenciales/image_default.png', upload_to='credenciales/'),
        ),
    ]
