# Generated by Django 5.0.2 on 2024-05-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0011_alter_empresa_id'),
        ('credenciales', '0004_alter_credenciales_empresas_favoritas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credenciales',
            name='empresas_favoritas',
            field=models.ManyToManyField(blank=True, to='corp.empresa'),
        ),
    ]
