# Generated by Django 5.0.2 on 2024-05-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0011_alter_empresa_id'),
        ('credenciales', '0005_alter_credenciales_empresas_favoritas'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciales',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='credenciales',
            name='empresas_favoritas',
            field=models.ManyToManyField(blank=True, null=True, to='corp.empresa'),
        ),
    ]
