# Generated by Django 5.0.2 on 2024-05-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0011_alter_empresa_id'),
        ('credenciales', '0006_credenciales_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credenciales',
            name='empresas_favoritas',
            field=models.ManyToManyField(blank=True, default=list, null=True, to='corp.empresa'),
        ),
    ]
