# Generated by Django 5.0.2 on 2024-05-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0011_alter_empresa_id'),
        ('credenciales', '0010_credenciales_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credenciales',
            name='empresas_favoritas',
            field=models.ManyToManyField(blank=True, to='corp.empresa'),
        ),
    ]
