# Generated by Django 5.0.2 on 2024-05-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciales', '0011_alter_credenciales_empresas_favoritas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credenciales',
            name='imagen',
            field=models.ImageField(default='credenciales/images/image_default.png', upload_to='credenciales/images/'),
        ),
    ]
