# Generated by Django 5.0.2 on 2024-05-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciales', '0013_alter_credenciales_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credenciales',
            name='imagen',
            field=models.ImageField(blank=True, default='credenciales/images/image_5.png', upload_to='credenciales/images/'),
        ),
    ]
