# Generated by Django 5.0.2 on 2024-05-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciales', '0014_alter_credenciales_imagen'),
        ('webscraping', '0009_remove_comentarioscomputrabajo_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credenciales',
            name='empresas_favoritas',
            field=models.ManyToManyField(blank=True, to='webscraping.empresa'),
        ),
    ]
